### ISSUE TITLE
Editing footer

### ISSUE THREAD

**Issue by ibrah5em** [ibrah5em/My-Productus#1]
## Footer should be:

*Crafted by: [ibrah5em](https://github.com/ibrah5em)*

```html
<footer class="site-footer" role="contentinfo">
            <div class="footer-content">
                <p class="credit">
                    Crafted by 
                    <a href="https://github.com/ibrah5em" target="_blank" rel="noopener noreferrer" class="github-link">
                        <span class="author-name">ibrah5em</span>
                    </a>
                </p>
            </div>
        </footer>
```

with this style:

```css

  .site-footer {
      margin-top: 3rem;
      padding: 1.5rem 0;
      border-top: 1px solid rgba(255, 255, 255, 0.1);
  }
  
  .footer-content {
      max-width: 600px;
      margin: 0 auto;
      text-align: center;
  }
  
  .credit {
      color: #A0A0C0;
      font-size: 0.9rem;
      letter-spacing: 0.5px;
  }
  
  .github-link {
      color: var(--text-color);
      text-decoration: none;
      transition: color 0.3s ease;
      display: inline-flex;
      align-items: center;
      gap: 4px;
  }
  
  .github-link:hover {
      color: var(--primary); /* Was using --primary-color */
  }

    .accent {
        color: var(--primary); /* Was using --primary-color */
        margin: 0 4px;
    }
    
    .author-name {
        font-weight: 600;
    }
    
    .glasses {
        font-style: normal;
        margin-left: 4px;
    }

```
